# Generated by Django 4.1.2 on 2022-11-05 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cemail', models.EmailField(max_length=100)),
                ('clocation', models.CharField(max_length=1000)),
                ('cphone', models.CharField(max_length=12, null=True)),
                ('cimage', models.ImageField(blank=True, upload_to='cprofile_img')),
                ('cdescription', models.CharField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nemail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=10)),
                ('exp_position_1', models.CharField(max_length=50)),
                ('exp_from_1', models.CharField(max_length=50)),
                ('exp_to_1', models.CharField(max_length=50)),
                ('exp_comp_1', models.CharField(max_length=50)),
                ('exp_location_1', models.CharField(max_length=50)),
                ('exp_about_1', models.CharField(max_length=50)),
                ('exp_position_2', models.CharField(max_length=50)),
                ('exp_from_2', models.CharField(default='00/00/0000', max_length=50)),
                ('exp_to_2', models.CharField(max_length=50)),
                ('exp_comp_2', models.CharField(max_length=50)),
                ('exp_location_2', models.CharField(max_length=50)),
                ('exp_about_2', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=1000)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('phone', models.IntegerField(default='0000000000')),
                ('category', models.CharField(default='Web Developer', max_length=50)),
                ('language', models.CharField(default='English', max_length=60)),
                ('address', models.CharField(default='my home', max_length=500)),
                ('dob', models.CharField(default='00/00/0000', max_length=50)),
                ('edu_type_1', models.CharField(max_length=50)),
                ('edu_marks_1', models.FloatField(max_length=4)),
                ('edu_percentage_1', models.CharField(max_length=12)),
                ('edu_branch_1', models.CharField(max_length=100)),
                ('edu_year_1', models.CharField(max_length=50)),
                ('edu_inst_1', models.CharField(max_length=100)),
                ('edu_location_1', models.CharField(max_length=100)),
                ('edu_about_1', models.CharField(default='my home', max_length=1000)),
                ('edu_type_2', models.CharField(max_length=25)),
                ('edu_marks_2', models.FloatField(max_length=4)),
                ('edu_percentage_2', models.CharField(max_length=12)),
                ('edu_branch_2', models.CharField(max_length=100)),
                ('edu_year_2', models.CharField(max_length=50)),
                ('edu_inst_2', models.CharField(max_length=100)),
                ('edu_location_2', models.CharField(max_length=100)),
                ('edu_about_2', models.CharField(default='my home', max_length=1000)),
                ('user_img', models.FileField(upload_to='userProfile')),
                ('resume', models.FileField(upload_to='userResume')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('acategory', models.CharField(max_length=50)),
                ('aemail', models.CharField(max_length=50)),
                ('aphone', models.CharField(max_length=50)),
                ('ajob_name', models.CharField(max_length=50)),
                ('acomp_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jposition', models.CharField(max_length=100)),
                ('jtype', models.CharField(max_length=50)),
                ('jcreated', models.DateTimeField(auto_now_add=True)),
                ('jlocation', models.CharField(default='Work From Home', max_length=500)),
                ('jsalary', models.IntegerField(default='7000')),
                ('jdesc', models.CharField(max_length=1000)),
                ('jcname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.company_profile')),
            ],
        ),
    ]
