# Generated by Django 4.1.2 on 2022-10-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexperience',
            old_name='username',
            new_name='user',
        ),
    ]
