# Generated by Django 4.1.2 on 2022-10-22 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jcreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='jlocation',
            field=models.CharField(default='Work From Home', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='jsalary',
            field=models.IntegerField(default='7000'),
        ),
        migrations.AddField(
            model_name='job',
            name='jtype',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='cphone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
