# Generated by Django 4.1.2 on 2022-10-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_job_jcreated_job_jlocation_job_jsalary_job_jtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='cimage',
            field=models.ImageField(blank=True, upload_to='cprofile_img'),
        ),
    ]
