# Generated by Django 4.1.2 on 2022-10-30 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intern', '0002_rename_username_userexperience_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('acategory', models.CharField(max_length=50)),
                ('aemail', models.CharField(max_length=50)),
                ('aphone', models.CharField(max_length=50)),
                ('ajob_name', models.CharField(max_length=50)),
                ('acomp_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
