# Generated by Django 4.1.2 on 2022-10-22 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_alter_company_profile_cimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jdesc',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
