# Generated by Django 4.1.2 on 2022-10-24 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intern', '0004_job_jdesc_alter_company_profile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('about', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('edu_type_1', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('Graduation', 'Graduation'), ('Master', 'Master'), ('Diploma', 'Diploma'), ('Post-Graduation', 'Post-Graduation')], max_length=25)),
                ('edu_marks_1', models.FloatField(max_length=4)),
                ('edu_percentage_1', models.CharField(choices=[('Percentage', 'Percentage'), ('CGPA', 'CGPA'), ('GPA', 'GPA')], max_length=12)),
                ('edu_branch_1', models.CharField(choices=[('Computer Science Engineering', 'Computer Science Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('GPA', 'GPA')], max_length=50)),
                ('edu_year_1', models.CharField(max_length=50)),
                ('edu_inst_1', models.CharField(max_length=100)),
                ('edu_location_1', models.CharField(max_length=100)),
                ('edu_type_2', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('Graduation', 'Graduation'), ('Master', 'Master'), ('Diploma', 'Diploma'), ('Post-Graduation', 'Post-Graduation')], max_length=25)),
                ('edu_marks_2', models.FloatField(max_length=4)),
                ('edu_percentage_2', models.CharField(choices=[('Percentage', 'Percentage'), ('CGPA', 'CGPA'), ('GPA', 'GPA')], max_length=12)),
                ('edu_branch_2', models.CharField(choices=[('Computer Science Engineering', 'Computer Science Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('GPA', 'GPA')], max_length=50)),
                ('edu_year_2', models.CharField(max_length=50)),
                ('edu_inst_2', models.CharField(max_length=100)),
                ('edu_location_2', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='userResume')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
