# Generated by Django 4.1.2 on 2022-10-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_company_profile_cimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='cimage',
            field=models.ImageField(null=True, upload_to='static/uploaded_image/%y'),
        ),
    ]
