# Generated by Django 4.1.2 on 2022-10-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0006_userdetails_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='edu_branch_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='edu_branch_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='edu_percentage_1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='edu_percentage_2',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='edu_type_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='edu_type_2',
            field=models.CharField(max_length=25),
        ),
    ]
