# Generated by Django 4.1.2 on 2022-10-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0007_alter_userdetails_edu_branch_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
    ]
