# Generated by Django 4.1.2 on 2022-10-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0008_remove_userdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='address',
            field=models.CharField(default='my home', max_length=500),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='phone',
            field=models.IntegerField(default='0000000000'),
        ),
    ]
