# Generated by Django 4.1.2 on 2022-10-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0009_userdetails_address_userdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='edu_about_1',
            field=models.CharField(default='my home', max_length=100),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='edu_about_2',
            field=models.CharField(default='my home', max_length=100),
        ),
    ]
