# Generated by Django 4.1.2 on 2022-10-13 05:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0010_alter_company_profile_cimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='cdescription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
