# Generated by Django 4.1.2 on 2022-10-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0011_alter_company_profile_cdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='cimage',
            field=models.ImageField(upload_to='cprofile_img'),
        ),
    ]
