# Generated by Django 4.1.2 on 2022-10-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0012_alter_company_profile_cimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nemail', models.EmailField(max_length=100)),
            ],
        ),
    ]
