# Generated by Django 4.1.2 on 2022-10-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0014_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='Full-Time', max_length=100),
        ),
    ]
