# Generated by Django 4.1.2 on 2022-10-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0015_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=5000),
        ),
    ]
