# Generated by Django 4.1.2 on 2022-10-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0016_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.CharField(default='Work From Home', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
